{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "helm-app.fullname" . }}-ing
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  labels:
    {{- include "helm-app.labels" . | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.ingress.dns }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ .Release.Name }}-helm-app-svc
              servicePort: http
{{- end -}}
