apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-app.fullname" . }}-secret
  labels:
    {{- include "helm-app.labels" . | nindent 4 }}
type: Opaque
data:
  PGPASSWORD: {{ .Values.pg.postgresqlPassword | b64enc | quote }}